### ISSUE TITLE
Intermittent Error on Bake - [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by vmxeo** [rlguy/Blender-FLIP-Fluids-Beta#217]
Three times now I've gotten the error below during a simulation bake in different scenes, causing the bake to pause. I'm able to successfully resume the bake. So far I haven't found a pattern, and as far as I can tell the file/folder path it refers to doesn't seem to exist.

```
Traceback (most recent call last):
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 1141, in bake
    __run_simulation(fluidsim, data, cache_directory, bakedata)
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 1079, in __run_simulation
    __write_simulation_output(domain, fluidsim, blender_frameno, cache_directory)
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 1039, in __write_simulation_output
    __write_frame_stats_data(cache_directory, fluidsim, frameno)
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 947, in __write_frame_stats_data
    with open(logpath, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\vmxeo\\AppData\\Local\\Temp\\untitled_flip_fluid_cache\\temp\\framestats000024.data'
Info: Error Baking Fluid Simulation
Info: [Errno 2] No such file or directory: 'C:\\Users\\vmxeo\\AppData\\Local\\Temp\\untitled_flip_fluid_cache\\temp\\framestats000024.data'. See system console for error info.
```

**Comment by rlguy** [comment]
Thanks for letting me know! I am wondering what kinds of storage the cache is located on. Solid state drive, hard disk drive, or network drive?

There seems to be problems with file access for users using hard disk drives and network drives. This might be related to this issue: #134

**Comment by vmxeo** [comment]
This is a hard disk drive.
