### ISSUE TITLE
Error on bake initalize: function 'FluidSimulation_is_temporarty_mesh_levelset_enabled' not found

### ISSUE THREAD

**Issue by vmxeo** [rlguy/Blender-FLIP-Fluids-Beta#230]
Just upgraded to 0.1.3b, and am getting the following error when I try to bake:

`Traceback (most recent call last):
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 1161, in bake
    __run_simulation(fluidsim, data, cache_directory, bakedata)
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 1089, in __run_simulation
    __update_animatable_properties(fluidsim, data, simulator_frameno)
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 854, in __update_animatable_properties
    __update_animatable_domain_properties(fluidsim, data, frameno)
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 838, in __update_animatable_domain_properties
    __set_property(fluidsim, 'enable_temporary_mesh_levelset', reserve_temp_grids)
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 628, in __set_property
    old_value = getattr(obj, pname)
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\pyfluid\fluidsimulation.py", line 1279, in enable_temporary_mesh_levelset
    libfunc = lib.FluidSimulation_get_preferred_gpu_device
  File "C:\Users\vmxeo\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\pyfluid\pyfluid.py", line 40, in __getattr__
    return getattr(self._lib, name)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\ctypes\__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\ctypes\__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'FluidSimulation_is_temporarty_mesh_levelset_enabled' not found
Info: Error Baking Fluid Simulation
Info: function 'FluidSimulation_is_temporarty_mesh_levelset_enabled' not found. See system console for error info.`

**Comment by rlguy** [comment]
Oh wow, how embarrassing. I spelled ‘temporary’ incorrectly. I don’t know how I didn’t run into this error.

I’m currently away from a computer right now, but I’ll get this patched as soon as possible. Hopefully within the next few hours.

**Comment by vmxeo** [comment]
No worries. That's what testing is for :)

**Comment by rlguy** [comment]
Hey, does restarting Blender fix this error for you?

I could only reproduce this error with these steps:
1. Install version 0.1.2b
2. Uninstall version 0.1.2b
3. Install version 0.1.3b
4. Attempt to bake a simulation (ERROR)

Restarting Blender fixes this for me. I think this is because Blender does not refresh all of the loaded addon scripts to version 0.1.3b. Version 0.1.2b has 'temporary' spelled incorrectly and that was corrected in version 0.1.3b.

**Comment by vmxeo** [comment]
Restarting Blender worked. Thanks.

**Comment by rlguy** [comment]
Great to hear! I have added a note to the wiki to restart Blender after uninstallation:
https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Addon-Installation-and-Uninstallation
