### ISSUE TITLE
Error or crash on bake in test case

### ISSUE THREAD

**Issue by jhowe-3d** [rlguy/Blender-FLIP-Fluids-Beta#241]
New to the beta and just loaded things up. Installed the plug-in to Blender 2.79b. Opened cascading_water test case and I don't see the FLIP_Fluid_Test_Case group in the Physics properties panel. No errors in the console appear until I press Bake, which after initializing, results in an unknown error. System console contains message below. I uninstalled and reinstalled the plugin, restarting Blender. I also ran the invisible_box test case and it plays the timeline and then crashes at around frame 500. 

Let me know what other information I can supply.

```

Read prefs: C:\Users\joel\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
Read blend: D:\FrameworkMedia\3d\FlipFluidsBeta\cascading_water_feature-lite.blend
------------------------------------------------------------
Fluid Engine Version 0.1.03b
This test build was created for jhowe.
Thank you for testing!
------------------------------------------------------------
03-Apr-2018 22h27m29s enablePreviewMeshOutput: 0.08
03-Apr-2018 22h27m29s setDomainOffset: -5.1 -4.9 -0.054841
03-Apr-2018 22h27m29s setDomainScale: 1
03-Apr-2018 22h27m29s disableDiffuseMaterialOutput
03-Apr-2018 22h27m29s addBodyForce: 0 0 -9.81
03-Apr-2018 22h27m29s setBoundaryFriction: 0.1
03-Apr-2018 22h27m29s setSurfaceSubdivisionLevel: 2
03-Apr-2018 22h27m29s setNumPolygonizerSlices: 7
03-Apr-2018 22h27m29s setMarkerParticleScale: 4.08
03-Apr-2018 22h27m29s setSurfaceSmoothingValue: 0.5
03-Apr-2018 22h27m29s setSurfaceSmoothingIterations: 2
03-Apr-2018 22h27m29s enableSmoothInterfaceMeshing
03-Apr-2018 22h27m29s setMinTimeStepsPerFrame: 1
03-Apr-2018 22h27m29s setMaxTimeStepsPerFrame: 8
03-Apr-2018 22h27m29s disableAdaptiveObstacleTimeStepping
03-Apr-2018 22h27m29s setMarkerParticleJitterFactor: 1
03-Apr-2018 22h27m29s setPICFLIPRatio: 0.25
03-Apr-2018 22h27m29s setCFLConditionNumber: 5
03-Apr-2018 22h27m29s enableExtremeVelocityRemoval
03-Apr-2018 22h27m29s setMaxThreadCount: 16
03-Apr-2018 22h27m29s enableOpenCLScalarField
03-Apr-2018 22h27m29s enableOpenCLParticleAdvection
03-Apr-2018 22h27m29s setPreferredGPUDevice:
03-Apr-2018 22h27m29s enableAsynchronousMeshing
03-Apr-2018 22h27m29s disableStaticSolidLevelSetPrecomputation
03-Apr-2018 22h27m29s disableTemporaryMeshLevelSet
03-Apr-2018 22h27m29s enableExperimentalOptimizationFeatures
03-Apr-2018 22h27m29s disableFluidParticleOutput
03-Apr-2018 22h27m29s disableInternalObstacleMeshOutput
03-Apr-2018 22h27m29s setMeshOutputFormatAsBOBJ
03-Apr-2018 22h27m29s addMeshObstacle: 0x29248766e20
03-Apr-2018 22h27m29s addMeshObstacle: 0x29248767730
03-Apr-2018 22h27m29s addMeshObstacle: 0x29248767110
03-Apr-2018 22h27m29s addMeshObstacle: 0x292487671e0
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924876bfa0
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924879dcf0
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924879e250
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924879ed60
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924879ede0
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924879a0b0
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924879e850
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924879e7b0
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924876bd80
03-Apr-2018 22h27m29s addMeshObstacle: 0x2924879a010
03-Apr-2018 22h27m29s addMeshObstacle: 0x292487673e0
03-Apr-2018 22h27m30s addMeshFluidSource: 0x29248793d20
03-Apr-2018 22h27m31s addMeshFluidSource: 0x29248792740
03-Apr-2018 22h27m31s initialize

Initializing Simulation:
------------------------------------------------------------
03-Apr-2018 22h27m31s

Initializing Simulation Grids:
        Grid Dimensions: 400 x 301 x 216
        Cell Size:       0.02
        Constructing MACVelocityField:  2.0779
        Constructing Level Sets:        3.781
        Constructing Weight Grid:       1.407
        Initializing OpenCL Objects:    0.7339

------------------------------------------------------------

OpenCL ParticleAdvector Device Info:
CL_DEVICE_NAME:                Fiji
CL_DEVICE_VENDOR:              Advanced Micro Devices, Inc.
CL_DEVICE_VERSION:             OpenCL 2.0 AMD-APP (2527.8)
CL_DRIVER_VERSION:             2527.8
CL_DEVICE_OPENCL_C_VERSION:    OpenCL C 2.0
CL_DEVICE_TYPE:                GPU
CL_DEVICE_MAX_CLOCK_FREQUENCY: 1050MHz
CL_DEVICE_MAX_COMPUTE_UNITS:   64
CL_DEVICE_GLOBAL_MEM_SIZE:     4294967296
CL_DEVICE_LOCAL_MEM_SIZE:      32768
CL_DEVICE_MAX_MEM_ALLOC_SIZE:  3422552064
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
CL_DEVICE_MAX_WORK_ITEM_SIZES: 1024 x 1024 x 1024

OpenCL ParticleAdvector Kernel Info:
CL_KERNEL_FUNCTION_NAME:                      trilinear_interpolate_kernel
CL_KERNEL_NUM_ARGS:                           5
CL_KERNEL_WORK_GROUP_SIZE:                    256
CL_KERNEL_LOCAL_MEM_SIZE:                     0
CL_KERNEL_PRIVATE_MEM_SIZE:                   0
CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE: 64

------------------------------------------------------------

OpenCL CLScalarField Device Info:
CL_DEVICE_NAME:                Fiji
CL_DEVICE_VENDOR:              Advanced Micro Devices, Inc.
CL_DEVICE_VERSION:             OpenCL 2.0 AMD-APP (2527.8)
CL_DRIVER_VERSION:             2527.8
CL_DEVICE_OPENCL_C_VERSION:    OpenCL C 2.0
CL_DEVICE_TYPE:                GPU
CL_DEVICE_MAX_CLOCK_FREQUENCY: 1050MHz
CL_DEVICE_MAX_COMPUTE_UNITS:   64
CL_DEVICE_GLOBAL_MEM_SIZE:     4294967296
CL_DEVICE_LOCAL_MEM_SIZE:      32768
CL_DEVICE_MAX_MEM_ALLOC_SIZE:  3422552064
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
CL_DEVICE_MAX_WORK_ITEM_SIZES: 1024 x 1024 x 1024

OpenCL CLScalarField Kernel Info:
CL_KERNEL_FUNCTION_NAME:                      compute_scalar_field_points
CL_KERNEL_NUM_ARGS:                           8
CL_KERNEL_WORK_GROUP_SIZE:                    256
CL_KERNEL_LOCAL_MEM_SIZE:                     0
CL_KERNEL_PRIVATE_MEM_SIZE:                   0
CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE: 64

CL_KERNEL_FUNCTION_NAME:                      compute_scalar_field_point_values
CL_KERNEL_NUM_ARGS:                           8
CL_KERNEL_WORK_GROUP_SIZE:                    256
CL_KERNEL_LOCAL_MEM_SIZE:                     0
CL_KERNEL_PRIVATE_MEM_SIZE:                   0
CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE: 64

CL_KERNEL_FUNCTION_NAME:                      compute_scalar_weight_field_point_values
CL_KERNEL_NUM_ARGS:                           8
CL_KERNEL_WORK_GROUP_SIZE:                    256
CL_KERNEL_LOCAL_MEM_SIZE:                     0
CL_KERNEL_PRIVATE_MEM_SIZE:                   0
CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE: 64

CL_KERNEL_FUNCTION_NAME:                      compute_scalar_field_levelset_points
CL_KERNEL_NUM_ARGS:                           8
CL_KERNEL_WORK_GROUP_SIZE:                    256
CL_KERNEL_LOCAL_MEM_SIZE:                     0
CL_KERNEL_PRIVATE_MEM_SIZE:                   0
CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE: 64

Traceback (most recent call last):
  File "C:\Users\joel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 1161, in bake
    __run_simulation(fluidsim, data, cache_directory, bakedata)
  File "C:\Users\joel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 1089, in __run_simulation
    __update_animatable_properties(fluidsim, data, simulator_frameno)
  File "C:\Users\joel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 851, in __update_animatable_properties
    __update_animatable_inflow_properties(data, frameno)
  File "C:\Users\joel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 597, in __update_animatable_inflow_properties
    __get_parameter_data(data.append_object_velocity_influence, frameno)
  File "C:\Users\joel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\bake.py", line 89, in __get_parameter_data
    raise IndexError()
IndexError
```

**Comment by rlguy** [comment]
Hey, this is because you are using the Beta version (**0.1.3b**) of the addon. The test case scenes will only work with the test suite version (**0.1.3t**). You will find a link to the test suite addon in your invite email:

![untitled](https://user-images.githubusercontent.com/4285191/38286172-bc47bdfe-3778-11e8-978a-09181dc4f090.jpg)

I'll add a note to the documentation ([How to Run a Test Case](https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/How-to-Run-a-Test-Case)) that the test case scenes will only work with the test suite version of the addon.

**Comment by jhowe-3d** [comment]
Oh, so RTFD? Got it. Thanks!
