### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tag_redraw'

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids-Beta#248]
I baked the simulation and simultaneously rendered the frame. The UV Image Editor window was opened in full-screen mode. An error has occurred:

```
Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\operators\bake_operators.py", line 203, in modal
    self._update_status(context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\operators\bake_operators.py", line 151, in _update_status
    context.area.tag_redraw()
AttributeError: 'NoneType' object has no attribute 'tag_redraw'

location: <unknown location>:-1

**Comment by rlguy** [comment]
Thanks for letting me know about this! This has been fixed and will be included in the next version (**0.1.4b**).
