### ISSUE TITLE
Statistics for baked frames disappeared

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids-Beta#280]
During baking, an error occurs:

```Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\operators\bake_operators.py", line 203, in modal
    self._update_status(context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\operators\bake_operators.py", line 143, in _update_status
    self._update_stats(context)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids\operators\bake_operators.py", line 119, in _update_stats
    frame_stats_dict = json.loads(frame_stats.read())
  File "C:\Program Project\Blender Foundation\Blender 2.79b\2.79\python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Project\Blender Foundation\Blender 2.79b\2.79\python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Project\Blender Foundation\Blender 2.79b\2.79\python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

location: <unknown location>:-1
```

After that, the statistics for the following frames ceased to save.
I baked 300 frames. 0-169 have statistics. 170-300 did not have any statistics.

**Comment by rlguy** [comment]
Hey thanks for reporting this! Do you still have the fluid cache for this simulation? If so, would you be able to upload the ```fluid_cache/temp``` directory for me to check?

It looks like the addon didn't properly write one of the stats files. When it tried to read the file, there was an error and the addon stopped being able to update the stats data.

**Comment by PavelBlend** [comment]
For some reason github refuses to load zip. So saved on Google Drive:
https://drive.google.com/file/d/1_SMh-tH_0aXHwFJ1Yb2wNhPLmPIVOK-R/view?usp=sharing

**Comment by rlguy** [comment]
Thanks for uploading, this was very useful information! This bug has been fixed and will be included in the release version.
