### ISSUE TITLE
Bad Image

### ISSUE THREAD

**Issue by EODEFX** [rlguy/Blender-FLIP-Fluids-Beta#6]
I believe I've installed flip correctly. Once I've loaded up any of the test scenes, I get a windows error:
![image](https://user-images.githubusercontent.com/5790613/36187043-c1f1a032-1110-11e8-8914-5bc5cbcc755a.png)
Here's what I'm getting from the system console:
`Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bl_flip_fluids_test_suite\bake.py", line 1149, in bake
    fluidsim = FluidSimulation(init_data.isize, init_data.jsize, init_data.ksize, init_data.dx)
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bl_flip_fluids_test_suite\pyfluid\fluidsimulation.py", line 65, in __init__
    self._init_from_dimensions(isize, jsize, ksize, dx)
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bl_flip_fluids_test_suite\pyfluid\method_decorators.py", line 68, in check_values
    return func(self, *args)
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bl_flip_fluids_test_suite\pyfluid\fluidsimulation.py", line 81, in _init_from_dimensions
    libfunc = lib.FluidSimulation_new_from_dimensions
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bl_flip_fluids_test_suite\pyfluid\pyfluid.py", line 39, in __getattr__
    self._lib = self._load_library("pyfluid")
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bl_flip_fluids_test_suite\pyfluid\pyfluid.py", line 57, in _load_library
    raise LibraryLoadError("Unable to load library: " + name)
bl_flip_fluids_test_suite.pyfluid.pyfluid.LibraryLoadError: 'Unable to load library: pyfluid'
Exception ignored in: <bound method FluidSimulation.__del__ of <bl_flip_fluids_test_suite.pyfluid.fluidsimulation.FluidSimulation object at 0x0000023C30FDF080>>
Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bl_flip_fluids_test_suite\pyfluid\fluidsimulation.py", line 88, in __del__
    libfunc = lib.FluidSimulation_destroy
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bl_flip_fluids_test_suite\pyfluid\pyfluid.py", line 39, in __getattr__
    self._lib = self._load_library("pyfluid")
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bl_flip_fluids_test_suite\pyfluid\pyfluid.py", line 57, in _load_library
    raise LibraryLoadError("Unable to load library: " + name)
bl_flip_fluids_test_suite.pyfluid.pyfluid.LibraryLoadError: 'Unable to load library: pyfluid'`

**Comment by rlguy** [comment]
Hey EODEFX, thanks for reporting this! I have seen this error message before. This error means that the fluid engine .dll was not able to be loaded.

Would you be able to try these solutions to resolve this issue?

## Check that you have the 64-bit version of Blender installed

Attempting to run the simulator on a 32-bit install of Blender can cause this error. You can check for a 32/64 bit install by selecting **Blender > Help > Save System Info**. Open the **sysinfo.txt** file and check for the Python version close to the top:

![sysinfo_python_version](https://user-images.githubusercontent.com/4285191/36189441-5ac30de6-1107-11e8-96ad-b852f221e06b.jpg)

 ## Reinstall Graphics Drivers

Try reinstalling your graphics drivers. In the past, it has been found that some Windows 10 updates have caused problems with loading OpenCL. Reinstalling graphics drivers solved the error in these cases.

***

Please let me know if any of these solutions fixed the error. If the error is still present, I'll look further into this issue.

**Comment by EODEFX** [comment]
Installing the newest video drivers from NVIDIA fixed it. Thank you.

**Comment by rlguy** [comment]
Great to hear that it's now working!

**Comment by tcheng00** [comment]
This worked for me as well.  Thanks.

**Comment by danthefatman09** [comment]
Hello!

I seem to be having a similar issue but can't figure out whats going on. I have updated my driver. Here is the console error:

Read prefs: C:\Users\Daniel\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
archimesh: Imported multifiles
archipack: ready
Load Handler: Convert Yafaray texture "Tex" with texture type: "NONE" to "NONE"
search for unknown operator 'RENDER_OT_render_still', 'RENDER_OT_render_still'
search for unknown operator 'RENDER_OT_render_animation', 'RENDER_OT_render_animation'
search for unknown operator 'RENDER_OT_render_view', 'RENDER_OT_render_view'
search for unknown operator 'RENDER_OT_render_still', 'RENDER_OT_render_still'
search for unknown operator 'RENDER_OT_render_animation', 'RENDER_OT_render_animation'
search for unknown operator 'RENDER_OT_render_view', 'RENDER_OT_render_view'
TypeError: PointerProperty(...) expected an RNA type, failed with: RuntimeError: , missing bl_rna attribute from 'RNAMetaPropGroup' instance (may not be registered)

Exception in module register(): 'C:\\Users\\Daniel\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\yafaray_v3\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Users\Daniel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\yafaray_v3\__init__.py", line 111, in register
    prop.register()
  File "C:\Users\Daniel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\yafaray_v3\prop\__init__.py", line 34, in register
    yaf_scene.register()
  File "C:\Users\Daniel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\yafaray_v3\prop\yaf_scene.py", line 1301, in register
    bpy.utils.register_class(YafaRayProperties)
ValueError: bpy_struct "YafaRayProperties" registration error: noise_control could not register

**Comment by rlguy** [comment]
Hi danthefatman09,

It looks like this error is unrelated to this issue thread. From the error message, the problems are coming from the Yafaray and Archimesh addons.

I would suggest trying to disable combinations of FLIP Fluids, Yafaray, and Archimesh addons to see if disabling any of these will resolve the error.

Another note: incorrect installation of the FLIP Fluids addon or a problem with how Blender installs addons can lead to conflicts in your Blender configuration. Check to see if this issue relates to your problem: #400 

If you thing this is an issue related to the FLIP Fluids addon, please open a new issue thread and I would be glad to help!

\- Ryan
