### ISSUE TITLE
blender.exe-Bad Image

### ISSUE THREAD

**Issue by ianofshields** [rlguy/Blender-FLIP-Fluids-Beta#94]
The following system warning message appeared on my attempting to "Run Test Case":

C:Users\ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_puite\pyfluid\lib\libblpyfluid.dll.a is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f

**This message needed to be clicked twice.**

**a blender message then appeared:**

'Unable to load library:pyfluid'. See system console for error info.

**The system console contained the following:**

Read prefs: C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
Read blend: C:\Users\Ian\Downloads\cascading_water_feature.blend
Traceback (most recent call last):
  File "C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_suite\bake.py", line 1149, in bake
    fluidsim = FluidSimulation(init_data.isize, init_data.jsize, init_data.ksize, init_data.dx)
  File "C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_suite\pyfluid\fluidsimulation.py", line 65, in __init__
    self._init_from_dimensions(isize, jsize, ksize, dx)
  File "C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_suite\pyfluid\method_decorators.py", line 68, in check_values
    return func(self, *args)
  File "C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_suite\pyfluid\fluidsimulation.py", line 81, in _init_from_dimensions
    libfunc = lib.FluidSimulation_new_from_dimensions
  File "C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_suite\pyfluid\pyfluid.py", line 39, in __getattr__
    self._lib = self._load_library("pyfluid")
  File "C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_suite\pyfluid\pyfluid.py", line 57, in _load_library
    raise LibraryLoadError("Unable to load library: " + name)
bl_flip_fluids_test_suite.pyfluid.pyfluid.LibraryLoadError: 'Unable to load library: pyfluid'
Exception ignored in: <bound method FluidSimulation.__del__ of <bl_flip_fluids_test_suite.pyfluid.fluidsimulation.FluidSimulation object at 0x000001FF0DDD7A20>>
Traceback (most recent call last):
  File "C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_suite\pyfluid\fluidsimulation.py", line 88, in __del__
    libfunc = lib.FluidSimulation_destroy
  File "C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_suite\pyfluid\pyfluid.py", line 39, in __getattr__
    self._lib = self._load_library("pyfluid")
  File "C:\Users\Ian\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\bl_flip_fluids_test_suite\pyfluid\pyfluid.py", line 57, in _load_library
    raise LibraryLoadError("Unable to load library: " + name)
bl_flip_fluids_test_suite.pyfluid.pyfluid.LibraryLoadError: 'Unable to load library: pyfluid'
Info: Error Baking Fluid Simulation
Info: 'Unable to load library: pyfluid'. See system console for error info.

**Comment by ianofshields** [comment]
Got it.
Updated Graphics drivers and all is now working.

Many thanks.

**Comment by rlguy** [comment]
Great to hear, thanks for updating me!

**Comment by ianofshields** [comment]
Many thanks.


Ian McGlasham
www.ianmcglasham.com
